package huntdocs

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"
)

func TestParseSeverity(t *testing.T) {
	tests := []struct {
		input   string
		want    Severity
		wantErr bool
	}{
		{"critical", SeverityCritical, false},
		{"high", SeverityHigh, false},
		{"medium", SeverityMedium, false},
		{"Critical", SeverityCritical, false},
		{"HIGH", SeverityHigh, false},
		{"invalid", 0, true},
		{"", 0, true},
	}

	for _, tc := range tests {
		got, err := ParseSeverity(tc.input)
		if tc.wantErr && err == nil {
			t.Errorf("ParseSeverity(%q) expected error", tc.input)
		}
		if !tc.wantErr && err != nil {
			t.Errorf("ParseSeverity(%q) unexpected error: %v", tc.input, err)
		}
		if got != tc.want {
			t.Errorf("ParseSeverity(%q) = %v, want %v", tc.input, got, tc.want)
		}
	}
}

func TestSeverityString(t *testing.T) {
	tests := []struct {
		sev  Severity
		want string
	}{
		{SeverityCritical, "critical"},
		{SeverityHigh, "high"},
		{SeverityMedium, "medium"},
		{Severity(99), "unknown"},
	}
	for _, tc := range tests {
		if got := tc.sev.String(); got != tc.want {
			t.Errorf("Severity(%d).String() = %q, want %q", tc.sev, got, tc.want)
		}
	}
}

func TestGapString(t *testing.T) {
	g := Gap{
		File:     "foo.go",
		Line:     10,
		Symbol:   "Foo",
		Kind:     KindFunc,
		Severity: SeverityHigh,
		Reason:   "missing doc",
	}
	want := "foo.go:10: [high] function Foo: missing doc"
	if got := g.String(); got != want {
		t.Errorf("Gap.String() = %q, want %q", got, want)
	}
}

func writeFile(t *testing.T, dir, name, content string) string {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestRun_DocumentedFile(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "good.go", `// Package good provides goodness.
package good

// Greet returns a greeting.
func Greet() string { return "hi" }
`)

	var out, errBuf bytes.Buffer
	gaps, err := Run(Opts{
		Path:        dir,
		MinSeverity: SeverityMedium,
		Out:         &out,
		Err:         &errBuf,
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(gaps) != 0 {
		t.Errorf("expected 0 gaps, got %d: %v", len(gaps), gaps)
	}
}

func TestRun_MissingFuncDoc(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "bad.go", `// Package bad is bad.
package bad

func Export() string { return "hi" }
`)

	gaps, err := Run(Opts{
		Path:        dir,
		MinSeverity: SeverityHigh,
		Out:         &bytes.Buffer{},
		Err:         &bytes.Buffer{},
	})
	if err != nil {
		t.Fatal(err)
	}

	found := false
	for _, g := range gaps {
		if g.Symbol == "Export" && g.Kind == KindFunc {
			found = true
		}
	}
	if !found {
		t.Error("expected gap for undocumented Export function")
	}
}

func TestRun_MissingTypeDoc(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "types.go", `// Package types has types.
package types

type Widget struct {
	Name string
}
`)

	gaps, err := Run(Opts{
		Path:        dir,
		MinSeverity: SeverityMedium,
		Out:         &bytes.Buffer{},
		Err:         &bytes.Buffer{},
	})
	if err != nil {
		t.Fatal(err)
	}

	var foundType, foundField bool
	for _, g := range gaps {
		if g.Symbol == "Widget" && g.Kind == KindType {
			foundType = true
		}
		if g.Symbol == "Widget.Name" && g.Kind == KindField {
			foundField = true
		}
	}
	if !foundType {
		t.Error("expected gap for undocumented Widget type")
	}
	if !foundField {
		t.Error("expected gap for undocumented Widget.Name field")
	}
}

func TestRun_SkipsUnexported(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "unexported.go", `// Package u is a test.
package u

func helper() string { return "hi" }

type internal struct{}
`)

	gaps, err := Run(Opts{
		Path:        dir,
		MinSeverity: SeverityMedium,
		Out:         &bytes.Buffer{},
		Err:         &bytes.Buffer{},
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(gaps) != 0 {
		t.Errorf("expected 0 gaps for unexported symbols, got %d: %v", len(gaps), gaps)
	}
}

func TestRun_SkipsTestFiles(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "foo.go", `// Package foo is tested.
package foo
`)
	writeFile(t, dir, "foo_test.go", `package foo

func TestSomething() {}

type TestHelper struct{}
`)

	gaps, err := Run(Opts{
		Path:        dir,
		MinSeverity: SeverityMedium,
		Out:         &bytes.Buffer{},
		Err:         &bytes.Buffer{},
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, g := range gaps {
		if g.File == filepath.Join(dir, "foo_test.go") {
			t.Errorf("should not report gaps in test files: %v", g)
		}
	}
}

func TestRun_SkipsGenerated(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "gen.go", `// Code generated by tool; DO NOT EDIT.
package gen

func BigExport() {}
`)

	gaps, err := Run(Opts{
		Path:        dir,
		MinSeverity: SeverityMedium,
		Out:         &bytes.Buffer{},
		Err:         &bytes.Buffer{},
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(gaps) != 0 {
		t.Errorf("expected 0 gaps for generated file, got %d", len(gaps))
	}
}

func TestRun_SeverityFilter(t *testing.T) {
	dir := t.TempDir()
	// Exported var (medium) and exported func (high).
	writeFile(t, dir, "mixed.go", `// Package mixed has stuff.
package mixed

var Exported = 42

func Undocumented() {}
`)

	// With high filter, should only get the func.
	gaps, err := Run(Opts{
		Path:        dir,
		MinSeverity: SeverityHigh,
		Out:         &bytes.Buffer{},
		Err:         &bytes.Buffer{},
	})
	if err != nil {
		t.Fatal(err)
	}

	for _, g := range gaps {
		if g.Severity < SeverityHigh {
			t.Errorf("got gap below minimum severity: %v", g)
		}
	}
}

func TestRun_DocQualityCheck(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "quality.go", `// Package quality tests doc quality.
package quality

// This function does things.
func DoStuff() {}
`)

	gaps, err := Run(Opts{
		Path:        dir,
		MinSeverity: SeverityMedium,
		Out:         &bytes.Buffer{},
		Err:         &bytes.Buffer{},
	})
	if err != nil {
		t.Fatal(err)
	}

	found := false
	for _, g := range gaps {
		if g.Symbol == "DoStuff" && g.Kind == KindFunc {
			found = true
		}
	}
	if !found {
		t.Error("expected doc quality gap for DoStuff (should start with symbol name)")
	}
}

func TestRun_MethodDoc(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "method.go", `// Package method tests methods.
package method

// Svc is a service.
type Svc struct{}

func (s *Svc) Handle() {}
`)

	gaps, err := Run(Opts{
		Path:        dir,
		MinSeverity: SeverityHigh,
		Out:         &bytes.Buffer{},
		Err:         &bytes.Buffer{},
	})
	if err != nil {
		t.Fatal(err)
	}

	found := false
	for _, g := range gaps {
		if g.Symbol == "Svc.Handle" && g.Kind == KindMethod {
			found = true
		}
	}
	if !found {
		t.Error("expected gap for undocumented Svc.Handle method")
	}
}

func TestRun_SortOrder(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "sort.go", `// Package sort tests ordering.
package sort

var A = 1
func Z() {}
func B() {}
`)

	gaps, err := Run(Opts{
		Path:        dir,
		MinSeverity: SeverityMedium,
		Out:         &bytes.Buffer{},
		Err:         &bytes.Buffer{},
	})
	if err != nil {
		t.Fatal(err)
	}

	if len(gaps) < 2 {
		t.Fatalf("expected at least 2 gaps, got %d", len(gaps))
	}

	// High severity gaps should come before medium.
	for i := 1; i < len(gaps); i++ {
		if gaps[i].Severity > gaps[i-1].Severity {
			t.Errorf("gaps not sorted by severity: %v before %v", gaps[i-1], gaps[i])
		}
	}
}

func TestRun_InterfaceType(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "iface.go", `// Package iface tests interfaces.
package iface

type Reader interface {
	Read() error
}
`)

	gaps, err := Run(Opts{
		Path:        dir,
		MinSeverity: SeverityHigh,
		Out:         &bytes.Buffer{},
		Err:         &bytes.Buffer{},
	})
	if err != nil {
		t.Fatal(err)
	}

	found := false
	for _, g := range gaps {
		if g.Symbol == "Reader" && g.Kind == KindIface {
			found = true
		}
	}
	if !found {
		t.Error("expected gap for undocumented Reader interface")
	}
}

func TestRun_ConstDoc(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "consts.go", `// Package consts has constants.
package consts

const MaxSize = 100
`)

	gaps, err := Run(Opts{
		Path:        dir,
		MinSeverity: SeverityMedium,
		Out:         &bytes.Buffer{},
		Err:         &bytes.Buffer{},
	})
	if err != nil {
		t.Fatal(err)
	}

	found := false
	for _, g := range gaps {
		if g.Symbol == "MaxSize" && g.Kind == KindConst {
			found = true
		}
	}
	if !found {
		t.Error("expected gap for undocumented MaxSize const")
	}
}

func TestRun_InvalidPath(t *testing.T) {
	_, err := Run(Opts{
		Path:        "/nonexistent/path/that/does/not/exist",
		MinSeverity: SeverityHigh,
		Out:         &bytes.Buffer{},
		Err:         &bytes.Buffer{},
	})
	if err == nil {
		t.Error("expected error for invalid path")
	}
}
