package analysis

import "testing"

func TestIsTestFile(t *testing.T) {
	tests := []struct {
		name string
		file string
		want bool
	}{
		{"test file", "foo_test.go", true},
		{"regular file", "foo.go", false},
		{"suffix mismatch", "foo_test.go.bak", false},
		{"test in path", "test/foo.go", false},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := IsTestFile(tc.file); got != tc.want {
				t.Errorf("IsTestFile(%q) = %v, want %v", tc.file, got, tc.want)
			}
		})
	}
}

func TestIsGeneratedFile(t *testing.T) {
	tests := []struct {
		name string
		src  string
		want bool
	}{
		{
			"generated first line",
			"// Code generated by foo; DO NOT EDIT.\npackage x",
			true,
		},
		{"not generated", "package x\n\nfunc f() {}", false},
		{
			"generated after block comment",
			"/* license */\n// Code generated; DO NOT EDIT.\npackage x",
			true,
		},
		{"generated after package", "package x\n// Code generated by foo", false},
		{"empty", "", false},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := IsGeneratedFile([]byte(tc.src)); got != tc.want {
				t.Errorf("IsGeneratedFile(%q) = %v, want %v", tc.src, got, tc.want)
			}
		})
	}
}

func TestIsLintSource(t *testing.T) {
	tests := []struct {
		file string
		want bool
	}{
		{"tools/lint/linter/foo.go", true},
		{"pkg/server/handler.go", false},
	}
	for _, tc := range tests {
		t.Run(tc.file, func(t *testing.T) {
			if got := IsLintSource(tc.file); got != tc.want {
				t.Errorf("IsLintSource(%q) = %v, want %v", tc.file, got, tc.want)
			}
		})
	}
}

func TestIsTestHelper(t *testing.T) {
	tests := []struct {
		file string
		want bool
	}{
		{"tests/errors/error.go", true},
		{"pkg/server/handler.go", false},
	}
	for _, tc := range tests {
		t.Run(tc.file, func(t *testing.T) {
			if got := IsTestHelper(tc.file); got != tc.want {
				t.Errorf("IsTestHelper(%q) = %v, want %v", tc.file, got, tc.want)
			}
		})
	}
}

func TestIsCmdSource(t *testing.T) {
	tests := []struct {
		file string
		want bool
	}{
		{"cmd/server/main.go", true},
		{"pkg/server/handler.go", false},
	}
	for _, tc := range tests {
		t.Run(tc.file, func(t *testing.T) {
			if got := IsCmdSource(tc.file); got != tc.want {
				t.Errorf("IsCmdSource(%q) = %v, want %v", tc.file, got, tc.want)
			}
		})
	}
}
