name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:

  lint:
    timeout-minutes: 10
    name: lint
    runs-on: ubuntu-latest-m
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: ./go.mod

      - name: Run Linters
        run: LINT_FIX=0 ./scripts/lint.sh

  test:
    timeout-minutes: 10
    name: test
    runs-on: ubuntu-latest-m
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: ./go.mod

      - name: Run Tests
        run: ./scripts/covgate.sh

  surface-lint:
    timeout-minutes: 10
    name: surface-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # yamllint disable rule:line-length
      - name: Lint YAML
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          file_or_dir: .
          config_file: .yamllint.yml

      - name: Lint Shell Scripts
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
        with:
          scandir: ./
          ignore_paths: .agents

      - name: Lint GitHub Actions Workflows
        uses: rhysd/actionlint@914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12
        # yamllint enable rule:line-length
